config/routes.rb
Rails4app::Application.routes.draw do
  resources :menus
  resources :users
  resources :orders do
    collection do
      get :recommend
    end
  end

  get "welcome/index"
  get "welcome/multiply_menu_ajax"

  root 'welcome#index'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
	has_many :orders
  scope :for_display, ->{ where(display: true) }
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :menu
  has_many :options

  class << self
    def today
      where(created_at:  Time.now.beginning_of_day ..Time.now).order(priority: :asc)
    end

    def today_soup
      today.
        where(priority: 0).
        map{|order|  order.options_by_option_sym(:soup)}.
        flatten.
        map(&:option)
    end
  end

  def option_remark
    if options.exists?(option_type: OPTION_CODES.index(:remark))
      options.where(option_type: OPTION_CODES.index(:remark)).first.remark
    end
  end

  def options_by_option_sym(sym)
    options.where(option_type: OPTION_CODES.index(sym))
  end

  def jp_options_by_option_sym(sym)
    if options_by_option_sym(sym).present?
      "#{options_by_option_sym(sym).map{|option| OPTION_HASH[sym][option.option]}.join(',')}"
    end
  end

  def jp_rice_amount
    RICE_AMOUNTS[amount]
  end

  def remark
    options.where(option_type: OPTION_CODES.index(:remark))
  end


  def to_jp_without_soup
    string = "#{menu.try(:name) || " *** nil *** "}の#{jp_rice_amount}"

    if jp_options_by_option_sym(:rice_option).present?
       string += jp_options_by_option_sym(:rice_option)
    end

    if option_remark
      string += ", #{option_remark}"
    end

    string
  end

  def to_jp
    string = to_jp_without_soup

    if jp_options_by_option_sym(:soup).present?
      string += ", #{jp_options_by_option_sym(:soup)}"
    end

    string
  end

  def option_creater(ary, sym)
    if ary.present?
      ary.each do |option|
        if sym == :remark
          self.options.create!(remark: option, option_type: OPTION_CODES.index(sym) )
        else
          self.options.create!(option: option, option_type: OPTION_CODES.index(sym) )
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :menus, through: :orders

  def today_orders
    orders.where(created_at:  Time.now.beginning_of_day ..Time.now).order(priority: :asc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/menus_controller.rb
# coding: utf-8

class MenusController < ApplicationController
  permits :name

  # GET /menus
  def index
    @menus = Menu.for_display
  end

  # GET /menus/1
  def show(id)
    @menu = Menu.find(id)
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit(id)
    @menu = Menu.find(id)
  end

  # POST /menus
  def create(menu)
    @menu = Menu.new(menu)

    if @menu.save
      redirect_to @menu, notice: 'Menu was successfully created.'
    else
      render action: 'new'
    end
  end

  # PUT /menus/1
  def update(id, menu)
    @menu = Menu.find(id)

    if @menu.update(menu)
      redirect_to @menu, notice: 'Menu was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /menus/1
  def destroy(id)
    @menu = Menu.find(id)
    @menu.display = false
    @menu.save

    redirect_to menus_url
  end
end

app/controllers/orders_controller.rb
# coding: utf-8

class OrdersController < ApplicationController
  permits :user_id, :menu_id, :amount, :priority

  # GET /orders
  def index
    @users = User.all
    begin
      @no_eat_users = User.all.pluck(:name) - Order.today.map{|order| order.user.name}
    rescue
    end
  end

  # GET /orders/1
  def show(id)
    @order = Order.find(id)
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit(id)
    @order = Order.find(id)
  end

  # POST /orders
  def create(order)
    @user = User.find(params[:order][:user_id])
    cookies.permanent[:user_id] = @user.id
    params[:menus].each_value.with_index do |menu_hash,i|
      order = @user.orders.create!(
        menu_id:  menu_hash[:menu_id],
        amount:   menu_hash[:amount_id],
        priority: i
      )
      order.option_creater((menu_hash[:rice_options]||[]).map(&:to_i), :rice_option)
      order.option_creater(menu_hash[:remark], :remark)
      order.option_creater((params[:soup_options]||[]).map(&:to_i), :soup)

    end

    redirect_to orders_path
  end

  # PUT /orders/1
  def update(id, order)
    @order = Order.find(id)

    if @order.update(order)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /orders/1
  def destroy(id)
    @order = Order.find(id)
    @order.destroy

    redirect_to orders_url
  end
end

app/controllers/users_controller.rb
# coding: utf-8

class UsersController < ApplicationController
  permits :name

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show(id)
    @user = User.find(id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit(id)
    @user = User.find(id)
  end

  # POST /users
  def create(user)
    @user = User.new(user)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  # PUT /users/1
  def update(id, user)
    @user = User.find(id)

    if @user.update(user)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy(id)
    @user = User.find(id)
    @user.destroy

    redirect_to users_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user_id = cookies.permanent[:user_id]
    @amount_hash = {"特盛" => 4, "大盛り" => 3, "普通" => 2, "少なめ" => 1, "ご飯1/3" => 0}
  end

  def multiply_menu_ajax
    @amount_hash = {"特盛" => 4, "大盛り" => 3, "普通" => 2, "少なめ" => 1, "ご飯1/3" => 0}
    @index = params[:index].to_i + 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{:href=>'//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css', :rel=>'stylesheet'}
    %link{:href=>'//netdna.bootstrapcdn.com/bootswatch/3.0.3/simplex/bootstrap.min.css', :rel=>'stylesheet'}

    %title Umart On Rails
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/menus/_form.html.haml
= simple_form_for(@menu) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/menus/edit.html.haml
%h1 Editing menu

= render 'form'

= link_to 'Show', @menu
\|
= link_to 'Back', menus_path

app/views/menus/index.html.haml
#main_container
  %h1 Listing menus

  %table
    %tr
      %th Name
      %th
      %th
      %th

    - @menus.each do |menu|
      %tr
        %td= menu.name
        %td= link_to 'Show', menu
        %td= link_to 'Edit', edit_menu_path(menu)
        %td= link_to 'Destroy', menu, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New Menu', new_menu_path

app/views/menus/new.html.haml
#main_container
  %h1 New menu

  = render 'form'

  = link_to 'Back', menus_path

app/views/menus/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @menu.name

= link_to 'Edit', edit_menu_path(@menu)
\|
= link_to 'Back', menus_path

app/views/orders/_form.html.haml
= simple_form_for(@order) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :menu_id
    = f.input :amount
    = f.input :priority

  .form-actions
    = f.button :submit

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
#main_container
  %h1 Listing orders

  %h2 一覧
  %table.table.table-striped
    %tr
      %th 削除
      %th 名前
      %th メニュー
      %th 希望度

    - @users.each do |user|
      - user.today_orders.each do |order|
        - if order.menu
          %tr
            %td= link_to 'Destroy', order, :method => :delete, :data => { :confirm => "#{user.name}さんの#{order.to_jp} (第#{order.priority + 1}希望) を本当に削除しますか？\nあなたは本当に #{user.name} さんですか" }
            %td= "#{user.name}さん"

            %td= "　#{order.to_jp}　"
            %td= "　(第#{order.priority + 1}希望)"
        - else
          %tr
            %td= "#{user.name}さん"
            %td *** nil ***
            %td
            %td

  %h2 今日食べない人
  %h3=@no_eat_users

  %h2 集計
  %ul
    - Order.today.where(priority: 0).order(menu_id: :asc).each do |order|
      %li
        %p= "#{order.to_jp_without_soup}"
  %table.soup
    %tr
      %td=Order.today_soup.count(0)
      %td=Order.today_soup.count(1)
    %tr
      %td 豚汁
      %td みそ汁

  %h3 03-3456-4074

app/views/orders/new.html.haml
%h1 New order

= render 'form'

= link_to 'Back', orders_path

app/views/orders/recommend.html.haml
#main_container
  - Menu.all.map{|m|[m.name, m.orders.count]}.sort_by{|(n, c)| c}.reverse.each.with_index do |(name, count), i|
    %div= "#{name}(#{count})#{'←これがおすすめ' if i == 0}"

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
#main_container
  %h1 Listing users

  %table
    %tr
      %th Name
      %th
      %th
      %th

    - @users.each do |user|
      %tr
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New User', new_user_path

app/views/users/new.html.haml
#main_container
  %h1 New user

  = render 'form'

  = link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/welcome/_add_menu_button.haml
%h3=link_to sanitize('<i class="fa fa-plus-circle"></i>') + " 第#{index + 1}希望を入力する。", welcome_multiply_menu_ajax_path(index: index), remote: true

app/views/welcome/_menu.haml
%h4
  = "第#{index}希望"
%table
  %tr.height50px
    %td メニュー:　
    %td
      = select_tag "menus[menu#{index}][menu_id]", options_from_collection_for_select(Menu.for_display, :id, :name), class: "form-control input-sm width400px"
      %button.random-button.top10px.btn{:disabled=>random_disabled ? :disabled : nil}
        ( ´•౪•`)&lt;ﾗﾝﾀﾞﾑ!
      %input.search.top10px.form-control{type: :text, placeholder: "検索..."}
      .result

  %tr.height50px
    %td ご飯の量:　
    %td
      - @amount_hash.each do |k, v|
        - if k == "普通"
          = radio_button_tag "menus[menu#{index}][amount_id]", v.to_i, {:checked => true}
        - else
          = radio_button_tag "menus[menu#{index}][amount_id]", v.to_i
        = " #{k}　"
  %tr.height50px
    %td ご飯のオプション:　
    %td
      = check_box_tag "menus[menu#{index}][rice_options][]", 0, false
      おかかごはん
      = check_box_tag "menus[menu#{index}][rice_options][]", 1, false
      めんたいごはん
  %tr.height50px
    %td
      任意オプション:　
      %br
      (ex.薄味,合鴨トッピング　
    %td= text_field_tag "menus[menu#{index}][remark][]", "", size: 75, class: 'form-control'

app/views/welcome/index.html.haml
#main_container
  %h1
    = succeed "mart" do
      %span{style: "color: red;"}> U
    = succeed "n" do
      %span{style: "color: blue;"} O
    = succeed "ails" do
      %span{style: "color: green;"} R
  %h3= "ただいまの注文は#{Date.today}扱いになります。"
  = form_for(Order.new) do |f|
    %table
      %tr.height50px
        %td 名前:　
        %td= f.select :user_id, options_from_collection_for_select(User.order(name: :asc), :id, :name, selected: @user_id),{}, class: "form-control input-sm width100px float-left"
      %tr.height50px
        %td
        %td
          %div= render partial: 'welcome/menu', locals: {index: 1, random_disabled: true}
          #menu_item_form
          #menu_item_button
            = render partial: 'welcome/add_menu_button', locals: {index: 1}
      %tr.height50px
        %td 汁物:　
        %td
          %div
            %span
              = check_box_tag 'soup_options[]', 0, false
              豚汁
              = check_box_tag 'soup_options[]', 1, false
              みそ汁

    = button_tag "submit", class: "btn top20px"

    %h1.top30px.text-center=link_to sanitize('<i class="fa fa-cloud"></i>') + "リコメンドエンジン" + sanitize('<i class="fa fa-cloud"></i>'), recommend_orders_path
    %h4.top50px
      %i.fa.fa-cog=link_to "注文管理", orders_path, class: 'left10px'
    %h4.top50px
      %i.fa.fa-user=link_to "ユーザー管理", users_path, class: 'left10px'
    %h4.top50px
      %i.fa.fa-apple=link_to "メニュー管理", menus_path, class: 'left10px'

app/views/welcome/multiply_menu_ajax.js.erb
$("#menu_item_form").append(
  "<%= j(render(partial: 'welcome/menu', locals: {index: @index, random_disabled: false})) %>");
$("#menu_item_button").html(
  "<%= j(render(partial: 'welcome/add_menu_button', locals: {index: @index})) %>");